### ISSUE TITLE
python_-m_insights.tools.cat reports: "/bin/python: No module named tools"

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#1697]
Old client:
~~~
root@vm37-39 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)
[root@vm37-39 ~]# rpm -qa | grep insights
redhat-access-insights-1.0.6-0.el7.noarch
[root@vm37-39 ~]# cat insights-vm37-39.gsslab.pek2.redhat.com-20190222010448/insights_commands/python_-m_insights.tools.cat_--no-header_rhev_data_center
/usr/bin/python: No module named insights.tools
~~~
New version client:
~~~
[root@liuxc-rhel-client-test ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.5 (Maipo)
[root@liuxc-rhel-client-test ~]# rpm -qa | grep insights
insights-client-3.0.3-9.el7_5.noarch
[root@liuxc-rhel-client-test ~]# cat insights-liuxc-rhel-client-test-20190222012531/insights_commands/python_-m_insights.tools.cat_--no-header_rhev_data_center
/bin/python: No module named tools
~~~

**Comment by xiangce** [comment]
I just reinstalled the client tool and this issue still there. @csams @bfahr - Would please take a look at it?

**Comment by bfahr** [comment]
The fix in #1698 will catch the error, but there's still a problem with the client egg build that needs to be fixed.  The path to the modules was added in #1639.  The problem in the client egg build is here: https://github.com/RedHatInsights/insights-core/blob/9cabaa5159651bd3efe8625fb821e225cc985a65/build_client_egg.sh#L15

**Comment by jhjaggars** [comment]
https://github.com/RedHatInsights/insights-core/commit/a442128998c39413f674a995dd81d0e493805704 should resolve this.

**Comment by xiangce** [comment]
Thank you @jhjaggars, for the updating. The `/bin/python: No module named tools` issue is gone, but a new issue comes:
~~~
[root@liuxc-insights-dev archives]# cat insights-liuxc-insights-dev-20190305222857/insights_commands/python_-m_insights.tools.cat_--no-header_*
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/lib/insights/last_stable.egg/insights/tools/cat.py", line 31, in <module>
ImportError: No module named coloramaTraceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/lib/insights/last_stable.egg/insights/tools/cat.py", line 31, in <module>
ImportError: No module named coloramaTraceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/lib/insights/last_stable.egg/insights/tools/cat.py", line 31, in <module>
ImportError: No module named colorama
~~~

Seems the https://github.com/RedHatInsights/insights-core/commit/84c0d279 fixed this new issue. But it's not released.

Will check it after the next release.

**Comment by xiangce** [comment]
The latest results are:
~~~
[root@liuxc-insights-dev tmp]# cat insights-liuxc-insights-dev-20190310212530/insights_commands/python_-m_insights.tools.cat_--no-header_*
Missing Dependencies:
    At Least One Of:
        insights.specs.default.DefaultSpecs.ceph_insights
        insights.specs.insights_archive.InsightsArchiveSpecs.ceph_insightsMissing Dependencies:
    At Least One Of:
        insights.specs.default.DefaultSpecs.rhev_data_center
        insights.specs.insights_archive.InsightsArchiveSpecs.rhev_data_centerMissing Dependencies:
    At Least One Of:
        insights.specs.default.DefaultSpecs.sapcontrol_getsystemupdatelist
        insights.specs.insights_archive.InsightsArchiveSpecs.sapcontrol_getsystemupdatelist
~~~

**Comment by miclark** [comment]
@kylape, @gravitypriest is this fixed by #1710?

**Comment by gravitypriest** [comment]
https://github.com/RedHatInsights/insights-core/pull/1728 should have fixed the colorama dep. Not sure about the most recent comment.

**Comment by xiangce** [comment]
@miclark - The current status are:
1. The original issue `/bin/python: No module named` has been **fixed** by https://github.com/RedHatInsights/insights-core/commit/a442128998c39413f674a995dd81d0e493805704
2. The second one about `colorama` was also **fixed** by #1721 
3. The latest one about `Missing Dependencies` is not fixed. (Tested on 12, Mar)

**Comment by xiangce** [comment]
FYI,
The last issue "Missing Dependencies" is still there.

**Comment by xiangce** [comment]
Just realized that the `Missing Dependencies` is not a problem, it's because of the dependencies is really missing. Will check it in an env that satisfies all dependencies.

**Comment by csams** [comment]
Hey @xiangce, just check to see if this issue has been resolved. Thanks!

**Comment by xiangce** [comment]
@csams - Thanks for the update.
